require('og-miller.lspconfig')
require('og-miller.auto-complete2')
require('og-miller.github-theme')
--require('onedark').load()
--require('og-miller.onedark')
require('og-miller.lualine')
require('og-miller.dev-icons')
--require('og-miller.indent-blankline')
require('og-miller.treesitter')
require('og-miller.treesitter-context')
require('og-miller.harpoon')

